name: Run parse.py and commit index.json

on:
  schedule:
    - cron: '0,30 10-23 * * *'
  # This schedule is in UTC. You may need to adjust the time for EST.

  # allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run parse.py
      run: python parse.py

    - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
